#### No.1 Traducir una secuencia de DNA
####
#### Crea una función que divida una secuencia de DNA en sus codones
#### correspondientes y luego crea otra función que permita traducir
#### dicha secuencia en una proteína. Utiliza la siguiente
#### tabla de codones como referencia.

ATGACAAAGTATGCATTAGTCGGTGATGTGGGCGGCACCAACGCACGTCTTGCTCTGTGTGATATTGCCA
GTGGTGAAATCTCGCAGGCTAAGACCTATTCAGGGCTTGATTACCCCAGCCTCGAAGCGGTCATTCGCGT
TTATCTTGAAGAACATAAGGTCGAGGTGAAAGACGGCTGTATTGCCATCGCTTGCCCAATTACCGGTGAC
TGGGTGGCGATGACCAACCATACCTGGGCGTTCTCAATTGCCGAAATGAAAAAGAATCTCGGTTTTAGCC
ATCTGGAAATTATTAACGATTTTACCGCTGTATCGATGGCGATCCCGATGCTGAAAAAAGAGCATCTGAT
TCAGTTTGGTGGCGCAGAACCGGTCGAAGGTAAGCCTATTGCGGTTTACGGTGCCGGAACGGGGCTTGGG
GTTGCGCATCTGGTCCATGTCGATAAGCGTTGGGTAAGCTTGCCAGGCGAAGGCGGTCACGTTGATTTTG
CGCCGAATAGTGAAGAAGAGGCCATTATCCTCGAAATATTGCGTGCGGAAATTGGTCATGTTTCGGCGGA
GCGCGTGCTTTCTGGCCCTGGGCTGGTGAATTTGTATCGCGCAATTGTGAAAGCTGACAACCGCCTGCCA
GAAAATCTCAAGCCAAAAGATATTACCGAACGCGCGCTGGCTGACAGCTGCACCGATTGCCGCCGCGCAT
TGTCGCTGTTTTGCGTCATTATGGGCCGTTTTGGCGGCAATCTGGCGCTCAATCTCGGGACATTTGGCGG
CGTGTTTATTGCGGGCGGTATCGTGCCGCGCTTCCTTGAGTTCTTCAAAGCCTCCGGTTTCCGTGCCGCA
TTTGAAGATAAAGGGCGCTTTAAAGAATATGTCCATGATATTCCGGTGTATCTCATCGTCCATGACAATC
CGGGCCTTCTCGGTTCCGGTGCACATTTACGCCAGACCTTAGGTCACATTCTGTAA



#### No.2 Extrae la información referente al Distrito Federal, Guadalajara y
#### Monterrey de las bases de datos del INEGI (están en tu bandeja del correo
#### electrónico) y genera un archivo .csv nuevo que contenga ese subconjunto
#### de datos.
